$ANSIBLE_VAULT;1.1;AES256
36356532656264613535663031323737626531313933373962323661616466383037313131373237
6466393263303439613064356533393837383864343464340a326366633364376239303638373866
62363930383063336264316165323430646136386531656231333162646665373961613130306664
6666653066663762330a353837346661363338313237656666356537383038333739353562643364
35313937313735653063393031306532303539386235363235653838323139363365636663623066
39336264623938623766336364323163656331346539326136323063646331303561373036396461
66323566626266353462626530343232313962396638663564386365613065633134393935316461
39303333353365626536356237336137343735666561306166316330623238643436666365383431
37623662613464643037653765363262313662343566663864396637316638666431666633643563
35623532633661666235326639376466393264366233626539356466333130323738653566346638
33353836313835333737316537623133363965656537393963663038333433336266303631646433
39323037383939636639306533653438656238616632376632313430656232656465346465303130
33633865343437303535313339326535396439373839383763643863343165373534303763653066
35386237616661316565333933366436633732306162333830326564353765353433333833656564
386265303863623437616365323163306466
